### ISSUE TITLE
Put chart options titles into the ChartConfigBase class?

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#25]
As @Joelius300 pointed out [here](https://github.com/Joelius300/ChartJSBlazor/pull/23#pullrequestreview-271875207), we can maybe put the `OptionsTitle` to `ChartConfigBase` because it is used in every chart.

Check https://www.chartjs.org/docs/latest/configuration/title.html.

Or did I read something wrong here?

**Comment by SeppPenner** [comment]
~~After doing some research on this (https://github.com/Joelius300/ChartJSBlazor/issues/46#issuecomment-519795096), it seems like this is used for all chart types except pie, doughnut and polar area. I would like to wait for an official answer of the Chart.Js guys on this topic from here: https://github.com/chartjs/Chart.js/issues/6452.~~

~~Afterwards, we can decide what to do with the labels.~~

Forget it, this is the chart options title, not the chart dataset title. I got confused...

**Comment by Joelius300** [comment]
Yes that title counts for every chart. However it's not actually in the root (`ChartConfigBase`) but in the options-suboption. See [here](https://www.chartjs.org/docs/latest/configuration/title.html#title-configuration) and [here](https://www.chartjs.org/docs/latest/configuration/title.html#example-usage):  

> The title configuration is passed into the options.title namespace

This means it actually belongs in [`BaseChartConfigOptions`](https://github.com/Joelius300/ChartJSBlazor/blob/master/ChartJs.Blazor/ChartJS/Common/BaseChartConfigOptions.cs).  
I already did this a month ago with [this commit](https://github.com/Joelius300/ChartJSBlazor/commit/ab363cc1cdb101627f8e0f3a4c4d4ad29d1c2d4f#diff-dc488653608af6b1bab84c97759e9dda).  

I will close this issue as there is nothing to be done.

**Comment by SeppPenner** [comment]
Ah, okay. Good to know. I haven't looked through the files for this yet :)
