### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#26]
We should make a roadmap and a plan who can do what.

After the doughnut chart rework is done, I would take the pie chart for me because those are quite similar.

**Comment by SeppPenner** [comment]
The pie chart is reworked as well: https://github.com/Joelius300/ChartJSBlazor/pull/30

**Comment by Joelius300** [comment]
In what form do you suggest a roadmap?  

A simple file with what we want to implement in the future? Or something with milestones and individual issues that are just linked to in one big issue?  

I'm (sadly) not very experienced in this kind of stuff so I'm open to your suggestions.

**Comment by SeppPenner** [comment]
I know that this is quite huge effort, but I would go like the Asp.NetCore team does it: Milestones for the releases and previews, but also affected `areas` like e.g. documentation as tags: https://github.com/aspnet/AspNetCore/issues

**Comment by Joelius300** [comment]
What areas would you create?  
Also do we have actual releases for which we can plan ahead? I mean we don't have any deadlines so our releases just come out when they're done.. with everything that's new.  
We could kind of change that by adding milestones for every chart there is. Then we'd have releases for all of those. What do you think?  
Also since blazor and .net core 3 are in preview, our library is also in preview; we can't change that. The big 1.0 release won't have many additional features.. it will just be 1.0 since blazor is finally 1.0.

**Comment by SeppPenner** [comment]
> We could kind of change that by adding milestones for every chart there is. Then we'd have releases for all of those. What do you think?

Yes, this is a good ides.

> We could kind of change that by adding milestones for every chart there is. Then we'd have releases for all of those. What do you think?

Sure. We only have to wait until September :)

**Comment by SeppPenner** [comment]
> What areas would you create?

I haven't seen this one, I don't know, one per chart type, a general one and one for documentation maybe?

**Comment by Joelius300** [comment]
Have you looked at the [projects](https://github.com/Joelius300/ChartJSBlazor/projects) I've created? I like those since we also have the To Dos right there. Do you think I should still create the milestones and have them basically mirrored with the projects? Also what about labels?

**Comment by SeppPenner** [comment]
I guess, it's okay to use the projects. This is actually a feature I haven't used yet. The benefit is that we can see the progress easily.

**Comment by SeppPenner** [comment]
I guess we can close this now.

My next steps are: Waiting for your (@Joelius300) review on https://github.com/Joelius300/ChartJSBlazor/pull/50 and afterwards directly doing https://github.com/Joelius300/ChartJSBlazor/issues/28 (To get rid of these major issues that affect all files).

**Comment by Joelius300** [comment]
If we're still in need of a Roadmap feel free to open this again but you're right, currently the projects are enough.  

Ps. I will go to review it now :)
