### ISSUE TITLE
Add the documentation of the original project (and adjust it if something has changed)

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#3]
I would really like to see the documentation of the original project here, too. This makes it easier to use the project. For a start, the Wiki or the Readme with some small exaples would be good.

**Comment by Joelius300** [comment]
Would you like to participate or should I just do it myself? There are a few things that changed from the original project mainly how datasets are handled. If you want you can add the documentation and I will look over it if everything is correct. If not, I will do it eventually but currently I don't have time for that :/

**Comment by SeppPenner** [comment]
I can try to provide the original documentation. If there is something that doesn't seem to work for me when I test it, I will adjust the documentation already.
