### ISSUE TITLE
Add support for datalabels plugin, if possible

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#34]
Maybe support https://github.com/chartjs/chartjs-plugin-datalabels.

I don't have an idea how at the moment, but it must be possible.

**Comment by Joelius300** [comment]
Very good idea. There are also other plugin which I'd really like to support.  

However I want to finish the charts first before we start with plugins :)

**Comment by SeppPenner** [comment]
Sure, it is just an idea. I have looked at how the plugins are integrated, but at the moment I don't know exactly how to do that in Blazor with the JSInterop.

**Comment by SeppPenner** [comment]
This will be tracked under https://github.com/Joelius300/ChartJSBlazor/issues/34 after the merge of both repositories.
