### ISSUE TITLE
Move changelog to extra file

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#35]
I would move the changelog to an extra file to avoid bloating the readme file.

**Comment by MindSwipe** [comment]
Seems like a good idea, I would however keep the latest change in the readme and link the changelog file with a sentence like "The full changelog can be found \[here\]\(path/to/changelog\)"

**Comment by SeppPenner** [comment]
> Seems like a good idea, I would however keep the latest change in the readme and link the changelog file with a sentence like "The full changelog can be found [here](path/to/changelog)"

Semms legit. I will provide a pull request.
