### ISSUE TITLE
Update information to include copying of files to wwwroot

### ISSUE THREAD

**Issue by Venando-a** [Joelius300/ChartJSBlazor#38]
This is only mentioned in the closed issue #13: https://github.com/Joelius300/ChartJSBlazor/issues/13#issuecomment-513724537

**Comment by Joelius300** [comment]
This is a known issue. See [Documentation adjustments (todo)](https://github.com/Joelius300/ChartJSBlazor/issues/15)

> Mention index.html (client side) vs _Host.cshtml (server side). Currently only _Host.cshtml is mentioned. This should be further adjusted once both client- and server-side samples are available.

> Mention how to use _content. Also link to the Known-Issues page for server-side static content consumption which is currently unsupported.

**Comment by SeppPenner** [comment]
@Venando-a Yeah, we know that. The library is not yet complete and has some issues. We might even find a way to make it unnecessary to copy the files.

**Comment by SeppPenner** [comment]
Er, I would keep this open @Joelius300. Just for reference.

@Venando-a I didn't mean to close this. Just being said that the library still is not fully functional and might be experimental in some cases.

**Comment by Joelius300** [comment]
Correct, we should not yet close this since it is a real concern and a valid request. It's also something we want to do so closing this seems like we've done it already.

**Comment by Joelius300** [comment]
Is the [current description](https://github.com/Joelius300/ChartJSBlazor#usage) in the readme understandable to you or do you have suggestions to improve it? @Venando-a 

We're still trying to get the issue fixed but this is the most we can do currently. Any feedback is appreciated :)

**Comment by Venando-a** [comment]
That looks good to me - many thanks
