### ISSUE TITLE
Line Charts only works with point data

### ISSUE THREAD

**Issue by Venando-a** [Joelius300/ChartJSBlazor#39]
When using LineChartDataset <Point> the dataset is correctly rendered, but when other data types (object, int32wrapper) are used, nothing is rendered. Should be possible as per documentation: https://www.chartjs.org/docs/latest/charts/line.html#data-structure

**Comment by MindSwipe** [comment]
Can you elaborate on your problem? Also can you post some of your code? A short example of what you have along with a explanation of what you expected vs what happened would help us immensely in re-creating your problem and helping you

**Comment by Joelius300** [comment]
Please elaborate. Did you use the correct axis (x: category, y: something not category)? Also did you follow the points mentioned in the chart.js page you linked? 

> When the data array is an array of numbers, the x axis is generally a category. The points are placed onto the axis using their position in the array. When a line chart is created with a category axis, the labels property of the data object must be specified.

**Comment by Venando-a** [comment]
While a dataset like this works:
```
 LineChartDataset<Point> item = new LineChartDataset<Point>
                {
                    Label = PLs[0].Col[1].ToString(),
                    BackgroundColor = "#5baa00",
                    BorderColor = "#eaeaea",
                    CubicInterpolationMode = "monotone",
                    Fill = false,
                    BorderWidth = 2,
                    PointRadius = 5,
                    PointBorderWidth = 1,
                    ShowLine = true
                };
item.AddRange(DataPrint.Cast<int>().Select((i, s) => new Point(s,i)).Take(14).ToList());
```
simply setting the data type to int and relying on the position within the array for the category does not work as the following dataset will cause no line or points to be rendered
```
 LineChartDataset<Int32Wrapper> item = new LineChartDataset<Int32Wrapper>
                {
                    Label = PLs[0].Col[1].ToString(),
                    BackgroundColor = "#5baa00",
                    BorderColor = "#eaeaea",
                    CubicInterpolationMode = "monotone",
                    Fill = false,
                    BorderWidth = 2,
                    PointRadius = 5,
                    PointBorderWidth = 1,
                    ShowLine = true
                };
item.AddRange(DataPrint.Cast<int>().Take(14).ToList());
```

**Comment by Venando-a** [comment]
As @Joelius300 said the problem was that the x-Axis was not categorical.
