### ISSUE TITLE
Adjust Cutoutpercent in pie and doughnut chart

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#43]
From https://github.com/Joelius300/ChartJSBlazor/pull/23:

Good idea: Using getters and setters to set the Cutoutpercent. I think we can keep that (not 100% sure yet, see comment about the summary below) however I think we should remove the bool and just put get => CutoutPercent > 0.
Also the summary has to be modified. It doesn't signal that it just changes the CutoutPercent but instead it seems like this is an independant property if it really is the complete opposite. That's also why I think the constructor would be a better choice since you can always change the CutoutPercent later if you wanted to.

**Comment by Joelius300** [comment]
Closing this since it's covered by https://github.com/Joelius300/ChartJSBlazor/issues/40
