### ISSUE TITLE
Changes from string to string[] and Color to Color[] in pie and doughnut chart

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#44]
From https://github.com/Joelius300/ChartJSBlazor/pull/23:

* For the colors this 100% makes sense. I'm not so sure about the BorderWidths though. First of all, since c# is strongly typed the user has to use a collection there. Again for the colors this only makes sense but when do you need to have different BorderWidths for different arcs?
I don't think that's going to be used really and if necessary we can just implement a wrapper which allows both an array or a single value (I can do that, that's easy).
I opt to change that back to int for the BorderWidths and open an issue where we discuss if we need/want a wrapper for values like this (I think there are other places this could be used as well).
* Also we really need to mention indexable-options in the summary and in our wiki, otherwise noone will understand those string[].
* Last thing here, these don't need to be readonly since they can be null. The defaults of chart.js will be used. Readonly should only be used when the user is only allowed to modify the value. Here it's completely legitimate to set it to null.

**Comment by Joelius300** [comment]
Please take a look at [this issue](https://github.com/Joelius300/ChartJSBlazor/issues/45) for discussion which will determine how we will proceed with this issue here.

**Comment by SeppPenner** [comment]
I will close this because this issue is handled in https://github.com/Joelius300/ChartJSBlazor/issues/45 (As well as all other indexable options everywhere, I guess).
