### ISSUE TITLE
Implement indexable options

### ISSUE THREAD

**Issue by Joelius300** [Joelius300/ChartJSBlazor#45]
In chart.js there is something called [Indexable options](https://www.chartjs.org/docs/latest/general/options.html#indexable-options). These apply to many properties/options. E.g. the dataset of the pie-chart has 8 out of 10 properties that are indexable ([source](https://www.chartjs.org/docs/latest/charts/doughnut.html#dataset-properties)).  

I think it would be quite easy to implement (at least with json.net. With the new one [this](https://github.com/dotnet/corefx/issues/39905) might make trouble).  

Here's a scratch (not tested but should work). It's fully generic so any type could be used.  
Maybe we'll need a non-generic base-class for serialization but that shouldn't be an issue.
```
class IndexableProperty<T>
{
    public object BoxedValue { get; }

    public IndexableProperty(T singleValue) => BoxedValue = singleValue;
    public IndexableProperty(T[] indexedValues) => BoxedValue = indexedValues;
}
```

Do we want/need to support this?  

Opinions and discussions are welcome.  

cc @SeppPenner

**Comment by SeppPenner** [comment]
We should support that, I guess. It doesn't seem to be an issue with `Json.Net`, you're right. For the porting to `Text.Json` I still would wait. I mean, it's not yet complete (and still in preview as far as I know?).

**Comment by Joelius300** [comment]
Okay I will add this in and do some testing with it.  

>  For the porting to Text.Json I still would wait.

Yes, we have to wait for that either way (and yes it's still in preview). There are a few things I have not yet found a workaround for. Please check the [test-repos](https://github.com/Joelius300/serialization-tests) and also the [issue with all the pending bugs/feature requests](https://github.com/Joelius300/serialization-tests/issues/1).

**Comment by SeppPenner** [comment]
> Okay I will add this in and do some testing with it.

Very good :)

The missing support for generic super class serialization was something I fell over as well when testing `Text.Json`.

**Comment by Joelius300** [comment]
I will implement `IndexableOptions` after updating everything to preview8.  
I have a few good ideas for implementing it with `System.Text.Json` but I have not yet been able to test these. I will keep this stuff in the test-repo and come back to it once we can remove json.net from our project.  
This means that I will probably implement it with json.net anyway.

**Some links and ressources which will help (me) to implement `IndexableOptions`:**

- Keep in mind to do the null check. The wrapper is not allowed to store a null-value. To represent a null value the user should use `null` directly instead of `new IndexableOption(null)`. Also, an array containing null values is allowed since .
- [This question](https://stackoverflow.com/questions/50313978/json-net-serialize-generic-type-wrapper-without-property-name) shows an interesting approach for wrappers (or at least the concept). Imagine an interface `IWrapper` which has a getter (method, see SO answer why) to a property `Value` of type `object`. It could be used for `ObjectEnum` (although the advantage isn't big there) and `IndexableOption` (would make sense but isn't necessary).

For the implementation with json.net:  
- [Docs page for non-generic JsonConverter](https://www.newtonsoft.com/json/help/html/CustomJsonConverter.htm)
- For the `CanConvert` method we need something like [this](https://stackoverflow.com/questions/982487/testing-if-object-is-of-generic-type-in-c-sharp).
- Since we aren't typesafe there, we'll probably need to get the `Value` property (or `BoxedValue`) by reflection and serialize it like that.
- [This question](https://stackoverflow.com/questions/50313978/json-net-serialize-generic-type-wrapper-without-property-name) shows a different approach, without reflection. Check for perfomance and so on when testing this.

For System.Text.Json:  
- I have already opened an issue to request some help about this. It's [here](https://github.com/dotnet/corefx/issues/40398)
- I have now gotten new ideas revolving around [JsonConverterFactory](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconverterfactory). The inspiration comes from the [JsonStringEnumConverter](https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Serialization/JsonStringEnumConverter.cs) of .net (untested yet).
- The factory will test if it can convert it (again, [this](https://stackoverflow.com/questions/982487/testing-if-object-is-of-generic-type-in-c-sharp) might help), it will get the encapsulated generic type and it will create a converter with that encapsulated generic type (we should be able to use [the one with which I tested stuff](https://github.com/Joelius300/serialization-tests/blob/master/IndexableOptionTests/Converters/IndexableOptionConverterGeneric.cs)) using reflection. This should work in theory.
- The biggest throwback is that it might still be impossible to actually get it to work with the `JsonConverterAttribute`, I think adding it to the `options.Converters` will work fine.

**Comment by SeppPenner** [comment]
I agree with you, this should be the next step after preview8 and the #50.

**Comment by Joelius300** [comment]
# Update (good one)

I've closed [the issue of me asking for help](https://github.com/dotnet/corefx/issues/40398) because I have found the solution. I have now both a json.net and a System.Text.Json solution. You can find both in the [test repos](https://github.com/Joelius300/serialization-tests), in the [IndexableOptionTests](https://github.com/Joelius300/serialization-tests/tree/master/IndexableOptionTests) (or in the issue I linked).  

Once I get the time I will implement this is in our library and update all the options this applies to.  
After that I think it would be a good time to publish a new nuget version.

**Comment by SeppPenner** [comment]
Great 👍 

> Once I get the time I will implement this is in our library and update all the options this applies to.
After that I think it would be a good time to publish a new nuget version.

Yes, good idea. I will check the other issues and check what I can do.

**Comment by Joelius300** [comment]
I think the indexable options are pretty much done in https://github.com/Joelius300/ChartJSBlazor/pull/67 now.  

But there is something I'm not quite sure how to handle..  
Currently all the `IndexableOption` properties are nullable. I have used `Nullable<>` everywhere so the  value is ignored when serialized if nothing is set. This goes back to the fact that `default(Nullable<>)` will always be a nullable-instance representing null. This is further optimized by the compiler and the runtime.

Now there are a few things going through my head.  

- `default` of any struct will set all its properties to their default as well. [Here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-structs), 4th paragraph.
- using `struct` seems appropriate because indexable option definitely have value semantics; there are no real operations, it's just a value of one or the other type. However, if we were to use `class` we wouldn't have to worry about `null`.
- if we look at the "rules" (e.g. [this SO question](https://stackoverflow.com/questions/521298/when-to-use-struct)), we can see that struct might not be the best for our use-case. 
  - It can't be immutable since you can always store a reference to the value you wrap in it.
  - Speed doesn't matter in our case because it's held in one place and there aren't any operations done on it (usually at least)
  - The memory footprint isn't important in our case. It couldn't really be determined anyway since you can store literally anything in an indexable option, including a huge byte-array for example.
  - It definitly has value-semantics (that's the reason I chose struct)
  - There's no need for inheritance and polymorphism so that's a plus for struct

In the last commit, I have added support for uninitialized values by adding another `bool` to signal if it's not yet initialized and doesn't contain a value. This also allows us to write `undefined` in json if there isn't a value (already implemented in the converter).

Now we can do either
- Use nullable for all the properties and have `null` be the default
- Don't use nullable since the default is supported as well now
- Make `IndexableOption` into a class (sealed preferably)

What do you think?

Tagging @SeppPenner, @MindSwipe

**Comment by SeppPenner** [comment]
If you ask me, I would go with `Don't use nullable since the default is supported as well now`.

`Use nullable for all the properties and have null be the default` seems to be a bit strange :)

I'm fine with using a struct here (The only _real_ point against the struct would be that it can't be immutable as you stated above, but still I don't see the real benefit of a class here).

**Comment by Joelius300** [comment]
Well the thing is, I don't see the real benefit of a struct either because we don't need speed or anything else that structs are good at. As a general rule you should always use class when in doubt and this might fall into this category.  
Keep in mind that we don't have any structs in our library currently even though many classes have value semantics. Using struct now would, in some way, violate habits which is another argument for not using struct at all.

I honestly think just using class is better because that way it's consistent with the other classes, we don't need to worry about how things are passed differently (which might cause serialization problems) and we also don't need to worry about the immutability. Also, using class here wouldn't break any rules if we care about that.

**Comment by SeppPenner** [comment]
> Keep in mind that we don't have any structs in our library currently even though many classes have value semantics. Using struct now would, in some way, violate habits which is another argument for not using struct at all.

That's a good point...

I guess you're right here. We should try to stay consistent and only use structs if it's absolutely necessary.

**Comment by Joelius300** [comment]
Good, I think we found a solution. I'll rework it to a class when I get time, do some testing and then merge it. 

After that we should start heading for a new nuget release. However there are two things I want to do first.
- Merge the js-bug-fix because it's already done and tested.
- Try to get the static-assets-consumption to work without copying it locally. My motivation for that is simply that a new plain blazor library already has this functionality and for some reason ours doesn't.

**Comment by SeppPenner** [comment]
> After that we should start heading for a new nuget release.

Yeay 👍 

> Merge the js-bug-fix because it's already done and tested.

What was that again?

> Try to get the static-assets-consumption to work without copying it locally. My motivation for that is simply that a new plain blazor library already has this functionality and for some reason ours doesn't.

This would be cool. It's quite ugly to copy this by hand...
