### ISSUE TITLE
Rework polar area chart.

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#49]
I will rework the polar area chart next as it seems to be the most related to the pie and doughnut.

**Comment by SeppPenner** [comment]
I have read through https://www.chartjs.org/docs/latest/charts/polar.html and it is quite similar to the pie chart type. The documentation is wrong (as it was for the pie and doughnut chart) when it comes to the Color and number arrays: https://github.com/chartjs/Chart.js/issues/6453.

**Comment by SeppPenner** [comment]
It's done in https://github.com/Joelius300/ChartJSBlazor/pull/50.

**Comment by Joelius300** [comment]
Good changes but no complete yet.  
I have left a review.
