### ISSUE TITLE
Rename PieDoughnutAnimation to ArcAnimation

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#51]
The `PieDoughnutAnimation` is used in:

* PieChartOptions
* PolarAreaChartOptions

I would suggest to rename it to `PiePolarAnimation` because the `doughnut chart` doesn't exist in our case as we treat it as a `pie chart`.

**Comment by SeppPenner** [comment]
This should be done after https://github.com/Joelius300/ChartJSBlazor/pull/50 is checked and merged to avoid issus.

**Comment by Joelius300** [comment]
Actually I would suggest `RadialAnimation`, `ArcAnimation` (this one's better). Those are a lot more generic and we don't need to associate them with either `Pie` nor `Polar`.

**Comment by SeppPenner** [comment]
I didn't have a good name for that. Yeah, ArcAnimation seems good. (The Chart.JS guys are using this term very often as well).

**Comment by Joelius300** [comment]
Will you include this update in https://github.com/Joelius300/ChartJSBlazor/pull/50? I think it fits there even though it requires changes in other files. Just put the renaming and the associated error-fixing in one commit.

**Comment by SeppPenner** [comment]
Sure, I can add this as well later.

**Comment by SeppPenner** [comment]
This is already fixed in https://github.com/Joelius300/ChartJSBlazor/pull/50/commits/15c0662ea72e4ab3e69217f19084c416992c1027 in https://github.com/Joelius300/ChartJSBlazor/pull/50.

**Comment by SeppPenner** [comment]
Just for reference, this is already done: https://github.com/Joelius300/ChartJSBlazor/blob/master/ChartJs.Blazor/ChartJS/Common/Properties/ArcAnimation.cs. (In #50 as I mentioned before).
