### ISSUE TITLE
Support callbacks

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#55]
### Describe the feature request
We should somehow make it possible to support callbacks (e.g. https://www.chartjs.org/docs/latest/configuration/tooltip.html#tooltip-callbacks).

### Which Blazor project type is your feature request related to?
- Client-Side
- Server-Side

### Describe the solution you'd like
Support for callbacks if possible. (I don't have an idea yet how to support them...

**Comment by Joelius300** [comment]
There currently is support for `OnClick` and `OnHover` for `Legend` (See [here](https://github.com/Joelius300/ChartJSBlazor/tree/master/ChartJs.Blazor/ChartJS/Common/Legends)).  

However I don't know if those still work as a lot of stuff around this subject has changed. It is a good start and we can use it to further implement the handlers. We'd also need to implement classes for the items that are passed into the function.  

This is a big feature but very desirable. However, I think we should focus on reworking all charts first. At least fix all mistakes we can find and add XML-docs. After that we can really focus on new (big) features like this.

**Comment by SeppPenner** [comment]
Sure, I just wanted to say that this feature is something really needed. (I need it at least 🏃).

**Comment by SeppPenner** [comment]
Will be tracked by https://github.com/mariusmuntean/ChartJs.Blazor/issues/41 after the merge.
