### ISSUE TITLE
Update to .NET Core 3.0 Preview 8

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#57]
Check https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/ for changes.

**Comment by Joelius300** [comment]
Let's do this after https://github.com/Joelius300/ChartJSBlazor/pull/50 and before https://github.com/Joelius300/ChartJSBlazor/issues/28 as mentioned [here](https://github.com/Joelius300/ChartJSBlazor/issues/26#issuecomment-520848047). I'll do it after merging https://github.com/Joelius300/ChartJSBlazor/pull/50.  

After that we really need to create a release to keep up with the changelog and also bring out a new nuget-version. We really have to document all the breaking changes and update the wiki (including samples and readme) before starting to work on other charts or new features!

**Comment by SeppPenner** [comment]
Most important thing here: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/#comments-702:

> In the migration steps, you also need to change any package references of Microsoft.AspNetCore.Components.Browser to Microsoft.AspNetCore.Components.Web https://www.nuget.org/packages/Microsoft.AspNetCore.Components.Web/

This killed my project today...

https://www.nuget.org/packages/Microsoft.AspNetCore.Components.Browser/ seems to be not switched to preview8 (Maybe this will never be updated because everything is in *.Web now?): 
**3.0.0-preview7.19365.7**

**Comment by SeppPenner** [comment]
It's fixed once https://github.com/Joelius300/ChartJSBlazor/pull/60 is merged and @Joelius300 verified that this can be run properly.
