### ISSUE TITLE
Add selection to which chart this applies to in issue templates

### ISSUE THREAD

**Issue by Joelius300** [Joelius300/ChartJSBlazor#66]
For the issue templates we should add "which charts does this bug/feature request apply to" or something like that instead of just "which version (client vs server)".

For bugs we need to have both ("which chart" and "which version"), for feature requests it will always affect both versions (client & server) so we only need "which chart" there.  

It should say something like "Which chart is your feature request related to?" (same for bug ofc) with a comment stating that you should list the charts or write "All".

**Comment by SeppPenner** [comment]
This is a good idea. I can do that.
