### ISSUE TITLE
Enable the wiki

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#7]
I guess, it would be a good idea to enable the wiki and add the documentation from the old project as well: https://github.com/mariusmuntean/ChartJs.Blazor/wiki. Currently, I cannot add it because I don't have access or the wiki is disabled.

**Comment by Joelius300** [comment]
I have enabled wiki write access for everyone. You should be able to add pages now.

**Comment by SeppPenner** [comment]
I have added the stuff from the original project to the wiki.
