### ISSUE TITLE
Customizable chart-update

### ISSUE THREAD

**Issue by Joelius300** [Joelius300/ChartJSBlazor#71]
### Describe the feature request
If I wanted to change how long it takes for the chart-update to render, I cannot do that because it's hardcoded in the js-file. The important js-code is the following:

```
myChart.chart.render({
    duration: 800,
    lazy: false,
    easing: 'easeOutBounce'
});
```

### Which charts does this feature request apply to?
All charts

### Describe the solution you'd like
I'd like to be able to call `Update` on the chart-components with some additional, optional parameters like the duration, if the update should be lazy (can be interrupted) and which easing style. These should be optional parameters so 1. you don't _have_ to supply them 2. you can only supply one or two if you want 3. you can see the default values 4. backwards-compatibility (not important in our case)

### Describe alternatives you've considered
Change the js on your own and link it statically but that's not desirable.

### Additional context
[Here](https://www.chartjs.org/docs/latest/configuration/animations.html) are the easing options and some more information we might need.

**Comment by TomaszGrzmilas** [comment]
Hi,

Can I take thin one ?

**Comment by Joelius300** [comment]
Sure you can.

I didn't mention this but it's not actually an Animation object described in that last link. It only supports the three options that I showed. Reference is [here](https://www.chartjs.org/docs/latest/developers/api.html#updateconfig).

Therefore we do want to use the three optional parameters and the last link is just a reference for the easing options. We don't create the `Animation` class (just in case you questioned why I didn't plan on using that).

**Comment by Joelius300** [comment]
If it's not clear already, Please do not create a Pull Request for this as the work on this repository has officially ended now (I'll do a last nuget for during the migration). This issue, along most others, will be migrated to the original repo and you can open a Pull Request there if you still feel like it.

Thank you for your contribution, I hope to see you again in the original repo :)
