### ISSUE TITLE
Testing the labels

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#72]
Not a bug, just a test.

I want to test if the labels are set correctly from https://github.com/Joelius300/ChartJSBlazor/pull/69/commits/1b4b8073f003d9c889ce16846b2a24abde2c99f1.

**Comment by SeppPenner** [comment]
It works 😄

**Comment by Joelius300** [comment]
Sorry, I didn't leave a comment on the PR. I already tested it and it seems to work. You can already see the added label even before submitting the issue btw.

**Comment by SeppPenner** [comment]
> Sorry, I didn't leave a comment on the PR. I already tested it and it seems to work.

Ah okay.

> You can already see the added label even before submitting the issue btw.

No, I can't... I guess you as the owner can see it though: 

![image](https://user-images.githubusercontent.com/9639361/64188514-debc8080-ce72-11e9-809b-9a2cac79b604.png)

**Comment by Joelius300** [comment]
Ahh of course. Yes when I open an issue, I can already see labels and projects etc so I knew it would work. Thanks for testing it though, I like the effort :)
