### ISSUE TITLE
Nuget package not updated yet to preview9

### ISSUE THREAD

**Issue by stefanloerwald** [Joelius300/ChartJSBlazor#79]
Thanks for making the library compatible with preview9. Could you please also update the nuget package? As of today, the nuget package is still in the preview8 state, while the main README.md refers to the preview9 state.

**Comment by SeppPenner** [comment]
Hi @stefanloerwald. We haven't updated the nuget package yet. The reason is that @Joelius300 wanted to solve the issue with the static assets needed to be copied manually (Check also https://github.com/aspnet/AspNetCore/issues/13854) before the next version.

**Comment by stefanloerwald** [comment]
Thanks for the update @SeppPenner!

**Comment by SeppPenner** [comment]
We decided to not wait until this is done because it probably takes to long. @Joelius300 will bring out a new nuget version soon.

**Comment by Joelius300** [comment]
I finally had time to upload the nuget :)

You can find it [here](https://www.nuget.org/packages/ChartJs.Blazor.Fork/0.10.3-preview). Keep in mind that I _just_ uploaded it so it might take a while for it to be available to you.
