### ISSUE TITLE
Fix outdated information in Wiki as well.

### ISSUE THREAD

**Issue by Joelius300** [Joelius300/ChartJSBlazor#8]
There's outdated information in the wiki along with some spelling errors (because it's just copied from the old project).  

These should get corrected if possible. Some things can be copied from the ReadMe, others may require some additional information.  

I will post a list of things that need to be changed when I get the time. For now fixing the code with the updated ReadMe and fixing the spelling errors is sufficient.

**Comment by SeppPenner** [comment]
Okay, I will see what I can do here 👍

**Comment by SeppPenner** [comment]
I have done it for now. Just tell me if you find anything else to change in the Wiki :)

**Comment by Joelius300** [comment]
Seems good. For each Chart I redo/update I will also include a sample-page from now on. So it would be nice to also have a documentation site for each Chart with a description on what to watch out for, tips and tricks, etc and the c#-sample itself.  

For now I will close the issue.
