### ISSUE TITLE
Implement missing special enums

### ISSUE THREAD

**Issue by Joelius300** [Joelius300/ChartJSBlazor#9]
### Caution
These might not be in the locations they're supposed to be. It might also not be the only location they are (supposed to be) in. This can be the case for all charts we've not reworked yet.  
Also the list might be incomplete.

- [ ] `FontStyle` in Labels.cs
- [ ] `BorderCapStyle` in LineDataset.cs
- [ ] `BorderJoinStyle` in LineDataset.cs
- [ ] `CubicInterpolationMode` in LineDataset.cs
- [ ] `PointStyle` in BubbleDataset.cs
- [ ] `BorderSkipped` in DoughnutDataset.cs
- [ ] `BorderAlign` in PieDataset.cs

**Comment by SeppPenner** [comment]
### Caution (edit 16.09)
The mentioned changes below were not merged and are still open!

### Original

* [x] FontStyle in Labels.cs: https://www.chartjs.org/docs/latest/axes/labelling.html. Can be `normal`, `italic`, `oblique`, `initial`, `inherit`.
* [x] BorderCapStyle in LineChartDataset.cs: https://www.chartjs.org/docs/latest/charts/line.html#line-styling. Can be: `butt`, `round`, `square`.
* [x] BorderJoinStyle in LineChartDataset.cs: https://www.chartjs.org/docs/latest/charts/line.html#line-styling. Can be `bevel`, `round`, `miter`.
* [x] CubicInterpolationMode in LineChartDataset.cs: https://www.chartjs.org/docs/latest/charts/line.html#cubicinterpolationmode. Can be `default`, `monotone`.
* [x] PointStyle in BubbleChartDataset.cs: https://www.chartjs.org/docs/latest/configuration/elements.html#point-styles. Can be `circle`, `cross`, `crossRot`, `dash`, `line`, `rect`, `rectRounded`, `rectRot`, `star`, `triangle`.

**Comment by SeppPenner** [comment]
There are some more like `BorderSkipped` or `BorderAlign`: https://github.com/Joelius300/ChartJSBlazor/issues/41.

**Comment by SeppPenner** [comment]
Done in https://github.com/Joelius300/ChartJSBlazor/pull/84.
