### ISSUE TITLE
Update to .NET Core 3.0 release

### ISSUE THREAD

**Issue by MindSwipe** [Joelius300/ChartJSBlazor#91]
# Rejoice, for .NET Core 3.0 has released

.NET Core 3.0 released a few days ago, I think we should update to it. This should be very easy as going from Preview 9 to release was primarily bug fixes https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/

**Comment by SeppPenner** [comment]
Good idea. I will just look through this because yesterday there was only a few dependencies on NetCore 3.0 already and the Blazor stuff was on NetCore3.0-preview9.19465.2 somehow... I will check this and report it back to here.

**Comment by SeppPenner** [comment]
This is what I was talking about:

![image](https://user-images.githubusercontent.com/9639361/65577976-30898f80-df75-11e9-8984-c6f8599b4233.png)

However, we still can update the stuff already, I have done that in my project and had no issues.

**Comment by MindSwipe** [comment]
This looks correct [here](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0/?utm_source=vs_developer_news&utm_medium=referral) they state that 

> This update to Blazor WebAssembly still has a Preview 9 version, but carries an updated build number

And they also say the latest Blazor WebAssembly version is preview9.19465.2

**Comment by SeppPenner** [comment]
Thanks for the update, I missed this post somehow.
