### ISSUE TITLE
Revival of original repository / end of life for this repository

### ISSUE THREAD

**Issue by Joelius300** [Joelius300/ChartJSBlazor#97]
As you might have seen, Marius M. (@mariusmuntean) has resumed work on the [original ChartJs.Blazor](https://github.com/mariusmuntean/ChartJs.Blazor). Since this repository here has made a lot of progress during the time the other project was abandoned, Marius has agreed on merging all my changes into his repository where all future development will be done.

This means that, after I have merged the remaining few pull request, this repo **will not be maintained anymore**. The [nuget package](https://www.nuget.org/packages/ChartJs.Blazor.Fork/) will be abandoned or removed entirely (if that's even possible). All the issues from here will be moved to the original repo.

The migration is currently taking place and me and Marius are actively working on it. We have a plan and are discussing important decisions and milestones along the way. For this reason I think it's best if people who want to contribute are very careful with what and where they open new issues and pull requests. You can always offer help but please do not rush anything as this is a slow and steady process which requires carefully planned execution.

If you already have bug-reports, new feature ideas or other stuff, please go ahead and open an issue in the original library as the issues here will have to be moved there manually anyway.

I'd like to thank all the contributors who helped me maintain this repo during the last three months.  
Special thanks go out to @SeppPenner who has been a great help. I'd also like to give special thanks to Marius himself for being so understanding and helpful concerning this library and the migration to his repository (and of course for making all of this possible in the first place).

I will continue to work on this library alongside Marius in his repo and adress the issues and feature that are still open/missing (either from issues in this repo, issues in the original repo or personal backlogs).  
Hope to see you there :)

**Comment by SeppPenner** [comment]
> I'd like to thank all the contributors who helped me maintain this repo during the last three months.
Special thanks go out to @SeppPenner who has been a great help. I'd also like to give special thanks to Marius himself for being so understanding and helpful concerning this library and the migration to his repository (and of course for making all of this possible in the first place).

Thank you for the kind words. I really like the library and want to contribute further on the original one from Marius as well 👍 

Just some thoughts from my side (I already told you some of them yesterday):

* Don't forget the wiki when migrating (Adjust all links as well)
* Contact @AdrienTorris under https://github.com/AdrienTorris/awesome-blazor once the migration is done
* Make this repository archived ~~and provide a hint to Marius' repository in the readme~~

I guess that's all from my side.

**Comment by TomaszGrzmilas** [comment]
Hi guys !

As I can see nothing is happening on mariusmuntean/ChartJs.Blazor repo. Maybe it was not good idea to kill this repository ? Here project was developing and I think now it will stuck in place :(

What you think ? Maybe we can still doing some work here ?

BR

**Comment by mariusmuntean** [comment]
Hi everyone,

I'm almost done with reintegrating the changes in my repo. The work I've done is on the `revival` branch.
Yesterday I republished the client-side samples on https://www.iloveblazor.com

Today I'll update the README and publish a NuGet package. Afterwards normal development should resume.

**Comment by Joelius300** [comment]
The migration is now officially complete 🎉 ❤️

This issue here will be closed but stay pinned for anyone who stumbles upon this repo. I might archive this repo but that's not fixed yet.

I hope to see everyone again back in the [original ChartJs.Blazor](https://github.com/mariusmuntean/ChartJs.Blazor) by [marius](https://github.com/mariusmuntean)! 😄
